### ISSUE TITLE
feature request: en and de in one request

### ISSUE THREAD

**Issue by csae8092** [acdh-oeaw/imprint-service#4]
the old imprint service returned on default both languages

```html
<div lang="en">
   ...
</div>
</div lang="de">
...
</div>
```

can we provide this feature in the new one as well, maybe using something like `?locale=all`

**Comment by stefanprobst** [comment]
what's the usecase for providing both languages on the same page?

**Comment by csae8092** [comment]
> what's the usecase for providing both languages on the same page?

exactly this, having both languages on the same page

**Comment by stefanprobst** [comment]
usually your website would be in either de or en, or it would allow to toggle website language. hence my question why you would ever need to display both on the same page.

**Comment by csae8092** [comment]
Because currently we show both in existing websites. But I can l can work around the current implementation
